version: '3'

services:

  backend:
    build: .
    environment:
      # APPLICATION
      - APPLICATION_ENV=dev
      - DEBUG_STATUS=true

      # DATABASE
      - DATABASE_URL=mysql:host=db;dbname=shows
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=password

    depends_on:
      - db
    volumes:
      - ./app:/app
    ports:
      - "8080:80"
    working_dir: /app/

  db:
    image: tutum/mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASS: password
      ON_CREATE_DB: shows
